# Camera
BOARD_CAMERA_SENSORS := ov8856 ov8865 s5k3l8 s5k3p3 s5k3p3_x50l
TARGET_COMPILE_WITH_MSM_KERNEL := true
BOARD_QTI_CAMERA_32BIT_ONLY := true
BOARD_QTI_CAMERA_V2 := true
TARGET_USE_VENDOR_CAMERA_EXT := true
USE_DEVICE_SPECIFIC_CAMERA := true
TARGET_TS_MAKEUP := true