# Init
TARGET_INIT_VENDOR_LIB := libinit_marmite
TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/
TARGET_RECOVERY_DEVICE_MODULES := libinit_marmite
TARGET_RELEASETOOLS_EXTENSIONS := $(DEVICE_PATH)/releasetools
